### ISSUE TITLE
why not simply have a branch for the stable version?

### ISSUE THREAD

**Issue by rweichler** [TheFakeMateo/RedPlusPlus#154]
instead of having a separate repo

**Comment by TheFakeMateo** [comment]
Because v3 and v4 are not even built on the same rom base anymore. v3 is a red hack, v4 is a crystal hack.

**Comment by rweichler** [comment]
gotcha.

**Comment by rweichler** [comment]
thanks for the explanation.

**Comment by FrostKnight** [comment]
> Because v3 and v4 are not even built on the same rom base anymore. v3 is a red hack, v4 is a crystal hack.

I assume then that you are waiting for the 9 bit version of pokemon polished crystal to be out to make similar changes?

Will it look the way pokemon red, blue and yellow looked graphically and musically? I loved the old graphics and dark feel of those games.

St.Anne was especially beautiful, I wish I could go on that more than once,

**Comment by JustRegularLuna** [comment]
It will not look like Gen 1, it honestly looks more like FireRed than Red, despite using Crystal as the base. Take a look at the map stitches in the notes folder.

**Comment by FrostKnight** [comment]
> It will not look like Gen 1, it honestly looks more like FireRed than Red, despite using Crystal as the base. Take a look at the map stitches in the notes folder.

That's disappointing, firered looks ugly to me. I like how pixelated gameboy games are. Oh well.

**Comment by Rangi42** [comment]
v3 already exists if that's what you prefer.

**Comment by FrostKnight** [comment]
Just felt like saying one more thing, doesn't fire red already exist? Just a thought

**Comment by JustRegularLuna** [comment]
It has the aesthetic that I want it to have. If that is not to your taste, I'm sorry, maybe it's not for you.

**Comment by JustRegularLuna** [comment]
The aesthetic change is one of the few modernizations that _wasn't_ scope creep, it was something I actually wanted. The other stuff, modernizing it beyond the point that I stopped caring about modern Pokémon games, is all scope creep because I spent too long not saying "no" to people. The aesthetic is staying, the other modern features I couldn't care less about. So you are barking up the wrong tree trying to get me to revert the aesthetic change. I'd rather revert everything else and keep the new aesthetic.

**Comment by FrostKnight** [comment]
> The aesthetic change is one of the few modernizations that _wasn't_ scope creep, it was something I actually wanted. The other stuff, modernizing it beyond the point that I stopped caring about modern Pokémon games (After Gen 3, I was just "going through the motions" and never really got into the new games anymore when I played them. And the aesthetic change is really the only update I like about FireRed. Never liked Sevii, never liked the storyline changes to add hand-holding, didn't like barring new pokemon behind the national dex, etc.), is all scope creep because I spent too long not saying "no" to people. The aesthetic is staying, the other modern features I couldn't care less about. So you are barking up the wrong tree trying to get me to revert the aesthetic change. I'd rather revert everything else and keep the new aesthetic.

Fair enough, I just didn't understand, as the whole changes you made confused me. I looked at them and didn't think much of them, but that's your taste not mine as you said.

Maybe someday someone will make what I desire off of 9 bit crystal.

**Comment by JustRegularLuna** [comment]
Maybe some day they will.

And I realize my response was probably confusing. A lot of people don't know that Red++ was not even supposed to be a "real hack" in the first place. I never set out to make a modernized version of Gen 1. I don't really even _want to play_ a modernized version of Gen 1, because I don't care about Gen 9 mechanics at all. Soul Silver was the last game Pokemon game I actually enjoyed, and I still replay GSC more often than HGSS.

Red++ started as me playing around with the pokered disassembly with no goal in mind at all except "practice Gameboy assembly code, so I can do cool things in my real hacks" (which mostly fell by the wayside because Red++ took over). And since the things I did for practice started with porting a few things from Gen 2 or whatever and fixing a few of the bugs, I decided to talk about it and release it. And then, because I was bad at telling people "no" when they asked for more and more things, scope creep kicked in, and it became something it was never intended to be. So instead of trying to reinvent the wheel on a bunch of features I have no interest in, I decided I should just switch to a different base instead of trying to code all of that on Gen 1. And added other things that I was actually interested in (such as the FireRed aesthetic, and the planned Johto post-game that I always wished FireRed had instead of Sevii) to try and keep myself interested in a project that was not even close to what it was supposed to be anymore.

So no, unfortunately, we don't want the same thing. But I'm sure there are other people who do want something similar to what you want, and maybe somebody will do it some day. If you want it badly enough, maybe you could do it yourself. But I have no interest in making a game that is aesthetically identical to Gen 1, while mechanically identical to the modern games.

**Comment by FrostKnight** [comment]
> Maybe some day they will.
> 
> And I realize my response was probably confusing. A lot of people don't know that Red++ was not even supposed to be a "real hack" in the first place. I never set out to make a modernized version of Gen 1. I don't really even _want to play_ a modernized version of Gen 1, because I don't care about Gen 9 mechanics at all. Soul Silver was the last game Pokemon game I actually enjoyed, and I still replay GSC more often than HGSS.
> 
> Red++ started as me playing around with the pokered disassembly with no goal in mind at all except "practice Gameboy assembly code, so I can do cool things in my real hacks" (which mostly fell by the wayside because Red++ took over). And since the things I did for practice started with porting a few things from Gen 2 or whatever and fixing a few of the bugs, I decided to talk about it and release it. And then, because I was bad at telling people "no" when they asked for more and more things, scope creep kicked in, and it became something it was never intended to be. So instead of trying to reinvent the wheel on a bunch of features I have no interest in, I decided I should just switch to a different base instead of trying to code all of that on Gen 1. And added other things that I was actually interested in (such as the FireRed aesthetic, and the planned Johto post-game that I always wished FireRed had instead of Sevii) to try and keep myself interested in a project that was not even close to what it was supposed to be anymore.
> 
> So no, unfortunately, we don't want the same thing. But I'm sure there are other people who do want something similar to what you want, and maybe somebody will do it some day. If you want it badly enough, maybe you could do it yourself. But I have no interest in making a game that is aesthetically identical to Gen 1, while mechanically identical to the modern games.

Well this answers a question I didn't ask. I wondered why you bothered to tweak the red version in the first place if your goal was to make a fire red look.

Since you don't have interest, I will just tell you why I had interest in having a polished crystal like pokered.

I don't expect you to change your mind, but in case you are curious, I decided to tell you.

I like the creepy feeling original pokemon red blue and yellow had. They have a dark ambient look, creepy stuff. fire red ruins this feeling and makes it look like a game for children. (which is what pokemon started looking after red/blue/yellow/green)

As a final note, good luck to you on your pursuit. I do wonder if it wouldn't be easier to modify fire red to get what you want though. But w/e

Have a good one.
