### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by TheRealPiggyWiggy** [TheFakeMateo/RedPlusPlus#20]
When i type make i get this C:\cygwin\usr\local\bin\rgbasm.exe: invalid option -- D
make: *** [Makefile:37: audio_red.o] Error 1

**Comment by TheFakeMateo** [comment]
Did you follow the instructions in INSTALL.md?

**Comment by TheRealPiggyWiggy** [comment]
yes

**Comment by TheFakeMateo** [comment]
If you have the right version of RGBDS, then I don't know why it would be giving you that issue :/ I've never run into that issue so I don't really know what to tell you...

**Comment by dannye** [comment]
Your rgbds is too old. You must have v0.2.3 or older. You should be using [v0.2.5](https://github.com/rednex/rgbds/releases/tag/v0.2.5).

**Comment by TheRealPiggyWiggy** [comment]
i have 0.3.1

**Comment by TheRealPiggyWiggy** [comment]
Thanks

**Comment by TheRealPiggyWiggy** [comment]
I am trying to look for MenuStrings in main.asm but its saying it does not exist

**Comment by TheFakeMateo** [comment]
Because it isn't in main.asm, it's in engine/menu/text_box.asm and it's been renamed to TwoOptionMenuStrings so github doesn't want to find it with MenuStrings for some reason.

**Comment by TheRealPiggyWiggy** [comment]
Can you update the game? and i found a glitch with the sgb border.
![dsasdz](https://user-images.githubusercontent.com/26042944/30505909-a80b9688-9a45-11e7-8311-4b9aa84dddfb.PNG)

**Comment by TheFakeMateo** [comment]
SGB border won't be in v3 anyway because it will be gbc-only.

**Comment by TheRealPiggyWiggy** [comment]
oh.

**Comment by TheFakeMateo** [comment]
Yep. That's why I haven't pushed many updates lately. Danny has been working on merging in the latest version of pokered-gbc in his branch, and once that happens, I can start getting to work taking advantage of it and pulling in some stuff I've already been testing on a copy of pokered-gbc. v3.0 will honestly have better graphics than Gen 2 did. The plan is to use non-snowy versions of the tilesets I made for Pokemon Christmas, so I've been working on getting some of those ready to pull in once that merge is done. SGB mode won't be supported anymore at that point, so that issue won't be an issue anymore.
