### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by DeckOfNoobs** [TheFakeMateo/RedPlusPlus#35]
when one of the trainers on route 24 says "I can see your feet from the grass" or whatever it is, it says "feat" instead of "feet"

**Comment by TheFakeMateo** [comment]
Sigh. That is not a typo. That is the original text from RBY and it actually does make sense. He doesn't say "I can see" he says "I saw your feat from the grass." In other words, he was in the grass, but he saw your accomplishment (taking out all the trainers on the bridge) from where he was standing. No, I'm not changing this, because there is nothing wrong with it.
